[workspace]
resolver = "2"
members = ["parenthesis", "parenthesis-macros"]

[workspace.package]
edition = "2021"
license = "Apache-2.0"

[profile.dev.package]
proptest.opt-level = 3
logos.opt-level = 3
